### ISSUE TITLE
NBPhoneNumber.h file not found

### ISSUE THREAD

**Issue by seenickcode** [mave/mave-ios-sdk#42]
I just downloaded the latest SDK and found this error in MAVEABPerson.m's list of includes.

**Comment by gregeinfrank** [comment]
@seenickcode That's from a pod dependency `libPhoneNumber-iOS`

**Comment by seenickcode** [comment]
Are there any other dependencies?   Which libPhoneNumber-iOS is it (there are multiple repos)?  Is there a way to create manual install instructions if one doesn't want to use Cococapods?  Thanks.

**Comment by gregeinfrank** [comment]
As  discussed offline, the correct repo is https://github.com/iziz/libPhoneNumber-iOS and we're currently on v0.8.3
