### ISSUE TITLE
Pushing View Controller on MAVEInvitePageViewController breaks after back button 

### ISSUE THREAD

**Issue by bvallelunga** [mave/mave-ios-sdk#50]
I wanted to add a extra share button which triggers your fallback share controller.
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/1920007/7581809/28ffa2ba-f83c-11e4-9c76-c7a301dfcbb8.png)

Code used:
``` swift
func showInvite(source: String) {
        MaveSDK.sharedInstance().presentInvitePageModallyWithBlock({ (viewController: UIViewController!) -> Void in
            if let inviteController = viewController.childViewControllers[0] as? MAVEInvitePageViewController {
                self.inviteController = viewController as! UINavigationController
                
                self.inviteController.navigationBar.tintColor = UIColor.blackColor()
                inviteController.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Action,
                    target: self, action: Selector("additionalShare"))
            }
            
            self.presentViewController(viewController, animated: true, completion: nil)
        }, dismissBlock: { (viewController: UIViewController!, numberOfInvitesSent: UInt) -> Void in
            self.dismissViewControllerAnimated(true, completion: nil)
        }, inviteContext: source)
    }
    
    func additionalShare() {
        var controller = MAVECustomSharePageViewController()
        var invite = self.inviteController.childViewControllers[0] as? MAVEInvitePageViewController
        
        self.inviteController.navigationBar.translucent = true
        self.inviteController.navigationBar.backgroundColor = UIColor.clearColor()
        self.inviteController.navigationBar.setBackgroundImage(UIImage(), forBarMetrics: UIBarMetrics.Default)
        self.inviteController.navigationBar.shadowImage = UIImage()
        self.inviteController.pushViewController(controller, animated: true)
    }
```

The problem is that after the user hits the back button when in the share controller, the search bar and the invite explanation logic breaks. The explanation isn't vertically centered and sometimes I get another copy of the search bar.

![slack_for_ios_upload-1](https://cloud.githubusercontent.com/assets/1920007/7581844/9051094a-f83c-11e4-9a6e-8158e44df043.png)
![slack_for_ios_upload-2](https://cloud.githubusercontent.com/assets/1920007/7581845/92fcd232-f83c-11e4-81e5-aedacdca4271.png)

**Comment by dcosson** [comment]
Cool hack to add sharing. I'll take a look at this - I've never tried pushing another view controller on top of the invitep age so not too surprised the layout breaks when you go back.

**Comment by bvallelunga** [comment]
Thanks, I read through your codebase to get it to work! I was modeling it off of lyfts share page. 
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/1920007/7603002/06abee44-f8e1-11e4-8fb6-58f02c390c93.png)

One think Lyft does which I think you SHOULD have, is the email. On Lyft you can select both email addresses and phone numbers and it will send the emails and phone numbers automatically. I also think your into messages `Brian Vallelunga sent you an invite: ` is very long, specially since we only have a limited number of characters before carriers split up the messages.

**Comment by bvallelunga** [comment]
I also think it would be cool if you could add a copy box like they have! The `Brian94803` box will copy it to your clipboard.

**Comment by dcosson** [comment]
I'm gonna push a new version today that should fix this issue.

The new version also adds a new invite page that we're calling invite page v3, it's slightly redesigned and includes email invites and the ability for a user to select all email addresses with one click. We're still experimenting so it won't be the default page for everyone just yet but email us at support@mave.io if you want us to turn it on for your app so you can try it out.

As for the copy box, we haven't included it quite yet but we have a few ideas to add the functionality soon.
