### ISSUE TITLE
Easy Way To Test

### ISSUE THREAD

**Issue by bvallelunga** [mave/mave-ios-sdk#51]
It would make using this SDK much easier to implement if we could easy test all the different view controllers.

ie: present MAVEInvitePageViewController, MAVECustomSharePageViewController, etc

It would also be cool if we could have someway to simulate a referral from the dashboard.

**Comment by dcosson** [comment]
The easiest way to test this currently is allow contacts permission and the contacts invite page view controller will be active. Then you can go to settings for your app, disable contacts access, then re-launch and the share page view controller will be active.

Would it be preferable if, say, there were a way on the dashboard to set the share page as the primary invite page?

As for simulating referrals, you can similarly do it manually. Send yourself an invite (you have to have your own phone number in your address book), then log out of your app or whatever you need to do so it'll be in the state you want to test the next time you open it, click the invite link when you get it, and then launch the app. The referring user passed in will be you.

It's an interesting idea to be able to simulate something like a referral from the dashboard, I'll think about how that might work. Do you have any thoughts on how you'd expect it to work?

**Comment by bvallelunga** [comment]
For testing the different controllers (share, invite, etc) I would just have a debug mode and then an override enum in the sdk.

```
mave.debug = true
mave.testController = .SharePage
```

As for simulating referrals from the dashboard, maybe have the ability to register test devices and then from the dashboard you can active the fingerprint for such device. Then I just run the app again from xcode and it will say I have a referral.

**Comment by dcosson** [comment]
I like this a lot. Currently thinking that simulating referrals might also be simplest as a debug option you can enable in the code, i.e. 

`mave.debugIncludeReferralUser = YES;`
`mave.debugReferralUserCustomData = @{@"foo": @1};`

Probably also makes sense to add a suggested invites debug flag too, that could just select a few random contacts from the list to show as suggestions.
