### ISSUE TITLE
Dropdown Popup Feature

### ISSUE THREAD

**Issue by bvallelunga** [mave/mave-ios-sdk#52]
It would be cool if you had an option for something similar to https://github.com/jmascia/KLCPopup

![687474703a2f2f692e696d6775722e636f6d2f42456d524762352e676966](https://cloud.githubusercontent.com/assets/1920007/7605513/3da0f86c-f905-11e4-9fe8-b5091500052d.gif)

**Comment by dcosson** [comment]
This is also cool, especially the way lyft has it where they pop it up after someone sends an invite. We'll keep it in mind
