### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by bvallelunga** [mave/mave-ios-sdk#54]
There should be a way to do deep linking similar to branchmetrics.io. I should be able to do
```
mave.createLink("images", [
      image: "<id>"
])
```

and then have a deeplink handler logic for when the app is/not installed.

**Comment by dcosson** [comment]
We may add something like this in the future but for now we're focused on our more specific use case than what branch offers, which is an awesome page that lets your users to send more, higher quality invites.

We'll definitely keep it in mind & in our potential backlog though, thanks for all these suggestions.
